#!/usr/bin/env bash

set -euo pipefail

if [ $# -gt 0 ]
then
  YEAR=$1
  shift
else
  YEAR=$(date +%Y)
fi

DIR="src/Y${YEAR}"
mkdir -p "$DIR"

if [ $# -gt 0 ]
then
  DAY=$1
else
  LAST_DAY=$(find "$DIR" -name 'Day*.hs' | sed -E 's!.+Day!!;s!\.hs!!' | sort -n | tail -n 1)
  DAY=$((LAST_DAY + 1))
fi

echo "Creating template for year $YEAR, day $DAY."

printf -v DAY0 "%02d" "$DAY"
FILE="$DIR/Day${DAY0}.hs"

cat > "$FILE" <<EOF
module Y${YEAR}.Day${DAY0} where

import qualified Data.Map  as Map
import qualified Data.Set  as Set
import qualified Data.Text as Text

import           AOC
import           Utils

part1 = error . show

parser :: Parser Text ()
parser = error "parser"

tasks =
  Tasks
    ${YEAR}
    ${DAY}
    ShowExamples
    parser
    [ Task part1 ()
    ]
EOF

git add "$FILE"

echo "Created $FILE."
