#!/usr/bin/env bash

set -euo pipefail

DAYS=$(find src -name 'Day*.hs' -print | sort)

{
    echo "module AllTasks where"
    echo "$DAYS" | sed 's!src/!import qualified !g;s!/!.!;s!.hs!!'
    echo "$DAYS" | sed '1 s!src/!allTasks = [ !;s!src/!           , !g;s!/!.!;s!.hs!.tasks!;$ s!$! ]!'
} >> "$3"
