#!/usr/bin/env bash

set -euo pipefail

case "$#" in
  1)
    LEVEL="$1"
    YEAR="$(date +%Y)"
    ;;
  2)
    YEAR="$1"
    LEVEL="$2"
    ;;
  *)
    echo "Usage: $0 [<year>] <level>" >&2
    exit 1
    ;;
esac

CACHE=.input-$YEAR-$LEVEL
if [ -f $CACHE ]
then
  cat $CACHE
  exit 0
fi

COOKIE_FILE=.session-cookie
if [ ! -f "$COOKIE_FILE" ]
then
  echo "Add your cookie to '$COOKIE_FILE'." >&2
  exit 1
fi
COOKIE=$(cat $COOKIE_FILE)

curl -sSL -o $CACHE -H "Cookie: session=$COOKIE" https://adventofcode.com/$YEAR/day/$LEVEL/input
cat $CACHE
