#!/usr/bin/env bash

set -euo pipefail

# Z3
if command -v dnf >/dev/null
then
  sudo dnf install -y z3-devel
elif command -v apt-get >/dev/null
then
  sudo apt-get update
  sudo apt-get install -y libz3-dev
elif command -v brew >/dev/null
then
  brew install z3
else
  echo "No package manager found." >&2
  exit 1
fi
