name:                aoc
version:             0.1.0.0
github:              koterpillar/aoc
license:             BSD3
author:              Alexey Kotlyarov
maintainer:          a@koterpillar.com
copyright:           2017-2021 Alexey Kotlyarov

extra-source-files:
- README.md

synopsis:            Advent of Code solutions

description:         Please see the README on Github at <https://github.com/koterpillar/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- html-entities
- http-conduit
- MissingH
- parsec
- split
- text
- time

default-extensions:
  - BangPatterns
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications

library:
  source-dirs: src

executables:
  day01:
    source-dirs: .
    main: day01.hs
    dependencies:
      - aoc

  day02:
    source-dirs: .
    main: day02.hs
    dependencies:
      - aoc

  day03:
    source-dirs: .
    main: day03.hs
    dependencies:
      - aoc

  day04:
    source-dirs: .
    main: day04.hs
    dependencies:
      - aoc

  day05:
    source-dirs: .
    main: day05.hs
    dependencies:
      - aoc
