name:                aoc
version:             0.1.0.0
github:              koterpillar/aoc
license:             BSD3
author:              Alexey Kotlyarov
maintainer:          a@koterpillar.com
copyright:           2017-2021 Alexey Kotlyarov

extra-source-files:
- README.md

synopsis:            Advent of Code solutions

description:         Please see the README on Github at <https://github.com/koterpillar/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- MissingH
- parsec
- text

library:
  source-dirs: .
