name:                aoc
version:             0.1.0.0
github:              koterpillar/aoc
license:             GPL-3
author:              Alexey Kotlyarov
maintainer:          a@koterpillar.com
copyright:           2017-2021 Alexey Kotlyarov

extra-source-files:
- README.md

synopsis:            Advent of Code solutions

description:         Please see the README on Github at <https://github.com/koterpillar/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- astar
- containers
- directory
- extra
- hashable
- html-entities
- http-conduit
- linear
- memoize
- microlens-platform
- MissingH
- mtl
- split
- text
- time
- vector
- unordered-containers

default-extensions:
  - BangPatterns
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeApplications

library:
  source-dirs: src

executables:
  main:
    source-dirs: main
    main: Main.hs
    dependencies:
      - aoc
