name: Renovate Lockfile Update

on:
  push:
    branches:
      - renovate/**

jobs:
  update-stack-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --dry-run
      - name: Update lockfile
        run: |
          if git diff --name-only | grep -q 'stack.yaml.lock'; then
            git config user.name "renovate[bot]"
            git config user.email "29139614+renovate[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.RENOVATE_GH_TOKEN }}@github.com/${{ github.repository }}
            git add stack.yaml.lock
            git commit -m "chore(deps): update lockfile"
            git push
          fi
